apiVersion: v1
kind: Pod
metadata:
  name: test-longhorn-pod
  namespace: speech
spec:
  imagePullSecrets:
    - name: local-registry-cred
  containers:
    - name: test
      image: local-registry:5000/cuda:12.9.1-cudnn-runtime-ubuntu24.04
      command: ["sleep", "3600"]
      volumeMounts:
        - name: vol
          mountPath: /data
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: test-longhorn-pvc