apiVersion: v1
kind: Pod
metadata:
  name: nvidia-smi-node1
  namespace: speech
spec:
  restartPolicy: Never
  runtimeClassName: nvidia
  nodeName: node1
  imagePullSecrets:
    - name: local-registry-cred
  containers:
    - name: nvidia-smi
      image: local-registry:5000/cuda:12.9.1-cudnn-runtime-ubuntu24.04
      imagePullPolicy: IfNotPresent
      command: ["nvidia-smi"]
      resources:
        limits:
          nvidia.com/gpu: 1
